[package]
name = "kiss3d_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.29"
nannou = "0.14"
nalgebra = "0.26"
rand = "0.7.3"


